export const UPDATE_SCHEMA = 'UPDATE_SCHEMA';
export const UPDATE_EPOCH = 'UPDATE_EPOCH';
export const UPDATE_ACTIVATION_FN_NAME = 'UPDATE_ACTIVATION_FN_NAME';

export const UPDATE_SAMPLES = 'UPDATE_SAMPLES';
export const UPDATE_BIAS = 'UPDATE_BIAS';
export const UPDATE_LEARNING_PROGRESS = 'UPDATE_LEARNING_PROGRESS';

export const UPDATE_VISUALIZE = 'UPDATE_VISUALIZE';
export const SKIP_TO_DEFAULT_LEARNING = 'SKIP_TO_DEFAULT_LEARNING';
export const VALIDATE_DATA_LEADNING_FILE = 'VALIDATE_DATA_LEADNING_FILE';
export const PART_OF_LEARNING_DATA = 'PART_OF_LEARNING_DATA';

export const START_LEARNING = 'START_LEARNING';
export const STOP_LEARNING = 'STOP_LEARNING';
