// @flow
export const SET_NOTIFICATION: 'SET_NOTIFICATION' = 'SET_NOTIFICATION';
export const CLEAR_NOTIFICATION: 'CLEAR_NOTIFICATION' = 'CLEAR_NOTIFICATION';
export const CLEAR_ALL_NOTIFICATION: 'CLEAR_ALL_NOTIFICATION' = 'CLEAR_ALL_NOTIFICATION';
